### ISSUE TITLE
file permissions issue in converter

### ISSUE THREAD

**Issue by nicolas-san** [ONLYOFFICE/Kubernetes-Docs#165]
I have followed the Helm install.

The trouble is with the files directory in the PVC

   ls -la /var/lib/onlyoffice/documentserver/App_Data/cache/
   total 12K
   drwxr-xr-x 3 ds ds 4.0K Jun 15 08:33 .
   drwxr-xr-x 4 ds ds 4.0K Jun 15 08:33 ..
   drwxr-xr-x 8 root root 4.0K Jul  1 09:40 files

The converter can't write the cache files

I've bypassed that with an initContainer to chown the directory, but it's temporary because I've edited the deployment directly in the cluster, and it's "hacky".

Do I miss something ?

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

Could you specify which Helm Chart DS version you are using and what storageClass is used to create PVC?

**Comment by nicolas-san** [comment]
I have use the helm chart available in this repo:
From the doc => helm repo add onlyoffice https://download.onlyoffice.com/charts/stable

For the storageClass, it's this one:
https://github.com/openebs/dynamic-nfs-provisioner

I'm not comfortable with the one you link in the doc since the chart is deprecated.

**Comment by GeorgeONLYOFFICE** [comment]
The issue is that DS containers work as ds user with UID and GID set to 101.
As OpenEBS NFS Provisioner create root user catalogues without write permissions for non owners, you can proceed as follows, setting these parameters below when installing Helm chart OpenEBS NFS

```
--set nfsStorageClass.filePermissions.UID=101
--set nfsStorageClass.filePermissions.GID=101
```

Alternatively, you may set mode=0777 instead of changing the owner, like this

```
--set nfsStorageClass.filePermissions.mode=0777
```
Please see [this section](https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/deploy/helm/charts/values.yaml#L107-L124) for your reference.
