### ISSUE TITLE
Fails to install when deploying with ArgoCD

### ISSUE THREAD

**Issue by tmiller** [ONLYOFFICE/Kubernetes-Docs#171]
Due to the way that ArgoCD converts the Helm hooks this chart fails to deploy in ArgoCD. In the chart on this [page](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks) one can see the `helm.sh/hook: pre-upgrade` get converted to a `argocd.argoproj.io/hook: PreSync` which gets executed on every sync. ArgoCD under the hood does not use helm in the way one would think. It's likely that other GitOps tools will have similar issues. This causes the job `pre-upgrade` to be executed on first run before the PVC it needs is created. It get's stuck in a progressing state and will not complete unless you selectively sync everything except the two applications.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/140352/179854125-db350e99-76a1-485d-a51c-8eaff4157b39.png">

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

We have checked ArgoCD and saw that its `pre-install` and `pre-upgrade` Hooks run at the same time which is not allowed when installing our chart, since the Job that runs during the update needs the application to be already installed and working.
At this point we'd recommend using FluxCD. We have tested this solution and it works with Helm natively, so there is no such issue. 

The possible solution to the problem in case with ArgoCD will be adding the possibility to turn on and off `pre-install` and `pre-upgrade` Jobs, depending on the scenario. 

We have implemented the following changes that are available at [this branch](https://github.com/ONLYOFFICE/Kubernetes-Docs/tree/feature/argocd). These changes will be added with the next release. 
Until then, you can test them using this branch.

Specifically, during the chart first-time installation you will need to set the following parameters

```
install:
  job:
    enabled: true

upgrade:
  job:
    enabled: false

```
Then, after the successful deployment of the application, prior to a subsequent synchronization, you will need to change the parameters like this

```
install:
  job:
    enabled: false

upgrade:
  job:
    enabled: true
```

and leave them this way.

**Comment by tmiller** [comment]
Thanks! This will work just fine for my use case. I appreciate the prompt reply.
