### ISSUE TITLE
Instruction how to add your own fonts

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Kubernetes-Docs#18]

**Comment by L3o-pold** [comment]
Any info on how to add custom fonts?

`documentserver-generate-allfonts.sh` seems missing.

**Comment by FROGGS** [comment]
Are there any news on that?

**Comment by GeorgeONLYOFFICE** [comment]
In order to add custom fonts, it's necessary to rebuild the images.
Thus the first step would be adding custom fonts at `fonts` directory and
then launch the images building script `build.sh`.
After this, it's required to specify your own repository and tag in the `image` parameters.
Finally, Helm ONLYOFFICE Docs installation should be performed, you can find more information about this
[here](https://github.com/ONLYOFFICE/Kubernetes-Docs#8-add-custom-fonts).

**Comment by FROGGS** [comment]
@GeorgeONLYOFFICE Does this also apply for the enterprise edition of the images?
